#cloud-config
ssh_pwauth: no
users:
  - name: yc-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOXToWig10YgHV18V1odo1SSklOqy2xY1iAI95nCOJMY vladb@DESKTOP-RHTFC6H"